### ISSUE TITLE
Frame indices out of bound?

### ISSUE THREAD

**Issue by Allen--Wu** [ffmpbgrnn/CMN#1]
For example, I noticed in train.list, that 
"weaving basket/uGK5IUDHiFI_001460_001470".

If you look into uGK5IUDHiFI, there are only 300 frames.

So could you expound on the format of these files?

**Comment by gzoumpourlis** [comment]
Hi Allen--Wu,
The original raw video on YouTube is this one:
https://www.youtube.com/watch?v=uGK5IUDHiFI
You can find the frames there by the indices that the annotation gives. Note that 1460 corresponds to *seconds*, not frames.
But I guess that you used a crawler that already chopped the videos in the 10-second snippets that the authors of CMN gave us.

**Comment by ffmpbgrnn** [comment]
Hi @Allen--Wu , as noted by @gzoumpourlis, this video has already been clipped to 10 second, which corresponds to 1460-1470 secs in the original video. Thanks.

**Comment by Allen--Wu** [comment]
Thank you all!
