### ISSUE TITLE
Some videos are unavailable.

### ISSUE THREAD

**Issue by jaypatravali** [ffmpbgrnn/CMN#3]
Hi,
I tried to get in touch with you over email since you have provided your contact in your README file.  I was able to only acquire 80% of the total dataset, rest were not available. Could you please help me download the entire datasets across 100 classes.

**Comment by ffmpbgrnn** [comment]
Hi @jaypatravali , I emailed the link for downloading to jaypatravali@gmail.com. Thank you.

**Comment by tonysy** [comment]
@ffmpbgrnn  Hi, could you share the download link to sy.zhangbuaa@gmail.com, thanks a lot.

**Comment by lovelyczli** [comment]
@ffmpbgrnn Thanks for your works! Could you share the download link to 1009440681@qq.com.  Thanks

**Comment by lzhangbj** [comment]
Hi, could you please send the download link to lzhangbj@connect.ust.hk? Thanks a lot. Some of the videos, hurling sport for example, are invalid.
